version: "2.18"

services:
  pgweb:
    image: sosedoff/pgweb
    restart: on-failure
    ports: 
      - "8081:8081" 
    links: 
      - postgres:fintech_database
    environment:
      DATABASE_URL: "postgres://root:1fintechpassword1@10.1.0.10:5432/fintech?sslmode=disable"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      fintech:
        ipv4_address: 10.1.0.25

  kowl:
      image: quay.io/cloudhut/kowl:latest
      restart: on-failure
      volumes:
        - ./kowl:/etc/kowl/
      ports:
        - "8080:8080"
      networks:
        fintech:
          ipv4_address: 10.1.0.20
      entrypoint: ./kowl --config.filepath=/etc/kowl/config.yaml
      depends_on:
        - kafka

  kafka:
    image: "bitnami/kafka:latest"
    restart: on-failure
    environment:
      ALLOW_PLAINTEXT_LISTENER: "yes"
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: "CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT"
      KAFKA_CFG_LISTENERS: "PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094"
      KAFKA_CFG_ADVERTISED_LISTENERS: "PLAINTEXT://kafka:9092,EXTERNAL://localhost:9094"
      KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE: "true"
    ports:
      - "9092:9092"
      - "9094:9094"
    networks:
      fintech:
        ipv4_address: 10.1.0.15

  postgres:
    image: "postgres:alpine"
    restart: on-failure
    environment:
      POSTGRES_DB: "fintech"
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "1fintechpassword1"
    ports:
      - "5432:5432"
    volumes:
      - fintech_database:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root -d fintech"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      fintech:
        ipv4_address: 10.1.0.10

networks:
  fintech:
    driver: bridge

    ipam:
      config:
        - subnet: 10.1.0.0/16
          gateway: 10.1.0.1

volumes:
  fintech_database:
    driver: local
