version: "2.18"

services:
  kafka:
    image: "bitnami/kafka:latest"
    environment:
      ALLOW_PLAINTEXT_LISTENER: "yes"
      KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE: "true"
    ports:
      - '9092:9092'
    networks:
      fintech:
        ipv4_address: 10.1.0.15

  postgres:
    image: "postgres:alpine"
    environment:
      POSTGRES_DB: "fintech"
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "1fintechpassword1"
    ports:
      - "5432:5432"
    volumes:
      - fintech_database:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root -d fintech"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      fintech:
        ipv4_address: 10.1.0.10

networks:
  fintech:
    driver: bridge

    ipam:
      config:
        - subnet: 10.1.0.0/16
          gateway: 10.1.0.1

volumes:
  fintech_database:
    driver: local